version: '3'
services:
  mongo:
    build: ./mongo
    image: docker_open5gs_mongo
    container_name: mongo
    volumes:
      - ./mongo:/mnt/mongo
      - ./mongodb:/var/lib/mongodb
    expose:
      - "27017/udp"
      - "27017/tcp"
    networks:
      default:
        ipv4_address: ${MONGO_IP}
  hss:
    build: ./hss
    image: docker_open5gs_hss
    container_name: hss
    env_file:
      - .env
    volumes:
      - ./hss:/mnt/hss
      - ./log:/open5gs/install/var/log/open5gs
    depends_on:
      - mongo
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
    ports:
      - "3000:3000/tcp"
    networks:
      default:
        ipv4_address: ${HSS_IP}
  sgw:
    build: ./sgw
    image: docker_open5gs_sgw
    container_name: sgw
    env_file:
      - .env
    volumes:
      - ./sgw:/mnt/sgw
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "2123/udp"
    ports:
      - "2152:2152/udp"
    networks:
      default:
        ipv4_address: ${SGW_IP}
  pgw:
    build: ./pgw
    image: docker_open5gs_pgw
    container_name: pgw
    env_file:
      - .env
    volumes:
      - ./pgw:/mnt/pgw
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "2152/udp"
      - "2123/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      default:
        ipv4_address: ${PGW_IP}
  mme:
    build: ./mme
    image: docker_open5gs_mme
    depends_on:
      - hss
      - sgw
      - pgw
    container_name: mme
    env_file:
      - .env
    volumes:
      - ./mme:/mnt/mme
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
    ports:
      - "36412:36412/sctp"
    networks:
      default:
        ipv4_address: ${MME_IP}
  pcrf:
    build: ./pcrf
    image: docker_open5gs_pcrf
    container_name: pcrf
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./pcrf:/mnt/pcrf
      - ./log:/open5gs/install/var/log/open5gs
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
    networks:
      default:
        ipv4_address: ${PCRF_IP}
networks:
  default:
    ipam:
      config:
        - subnet: ${TEST_NETWORK}
