version: '3'
services:
  ueransim:
    build: ./ueransim
    image: docker_ueransim
    container_name: ueransim
    stdin_open: true
    tty: true
    volumes:
      - ./ueransim:/mnt/ueransim
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    expose:
      - "38412/sctp"
      - "2152/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      default:
        ipv4_address: ${GNB_UE_IP}
networks:
  default:
    external:
      name: docker_open5gs_default
